plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - CPP.md
  - SAA.md
  - OCIFA.md

#remote_theme: "dracula/gh-pages"

theme: jekyll-theme-midnight
